### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Maelow** [HannibalZA/osTicket-Custom-Code#1]
1. I downloaded phar
2. Installed
3. Turned on
4. Created a setting (activated)
5. Added CSS from the example

Nothing has changed on my site. Am I doing something wrong?

sorry, I don't understand PHP

**Comment by HannibalZA** [comment]
Just confirm that you've enabled the instance as well as the plugin itself. It should work fine from there.

If that is all done, confirm that include/client/header.inc.php is writable since the plugin needs to access that file when saving.

**Comment by TheFatherMind** [comment]
I am confused... Is this in a doc or setup directions somewhere that I cannot find?  I just spent an hour and a half trying to figure out why this was not working... ^^ THIS was what was wrong.  The container I am running this from is storing the file as root with group and other not writable.  I would like to request that you note this somewhere in the plugin or setup directions or maybe have the plugin kick out an error if it is unable to modify the header file.

Also!  Thank you!! IDK why the ability to customize the CSS is not built into the app by now.
