### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by kMikaZu** [HannibalZA/osTicket-Custom-Code#3]
Is it possible to add a `.css` sample to make the navbar responsive?

**Comment by HannibalZA** [comment]
That's a tricky one, as it will require inserting additional markup into the base templates themselves.

At this point this plugin allows for manipulation/styling of the existing templates and markup.

Of course it should be perfectly possible to do this using a mixture of JS and CSS to change how the existing `ul.nav` behaves.

see the below link for a simple start:
https://www.w3schools.com/howto/howto_js_topnav_responsive.asp

**Comment by kMikaZu** [comment]
Probably gonna move to Zammad, since the promise of a 2.0 version for osTicket is a never-ending story...
